spring:
  application:
    name: wallet-auth-service

  # ========================
  # Database Configuration
  # ========================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:wallet_auth_db}
    username: ${DB_USERNAME:wallet}
    password: ${DB_PASSWORD:wallet123}

  # ========================
  # Redis Configuration
  # ========================
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:2s}

  # ========================
  # gRPC Configuration
  # ========================
  grpc:
    client:
      wallet-service:
        address: static://localhost:9090
        negotiation-type: plaintext
    server:
       port: 9091

  # ========================
  # Kafka Configuration
  # ========================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: wallet-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

# ========================
# Server Configuration
# ========================
server:
  port: ${SERVER_PORT:8083}

# ========================
# Custom JWT Configuration
# ========================
jwt:
  secret: ${JWT_SECRET:QuoocsCuongwf_EFEWalletProject_AuthService_SecretKey_ChangeThisToAtLeast64BytesLong}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
app:
  security:
    internal-secret-key: "EFEWallet_Super_Secret_Key_For_Internal_Microservices_2026@!"