"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import { Loader2, ShieldCheck } from "lucide-react"
import { toast } from "sonner"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { OtpInput } from "@/components/otp-input"
import { getErrorMessage } from "@/lib/api"
import { requestOtp, transfer, type TransferInput } from "@/lib/services"

const RESEND_SECONDS = 60

const currency = new Intl.NumberFormat("vi-VN", {
  style: "currency",
  currency: "VND",
  maximumFractionDigits: 0,
})

type TransferOtpModalProps = {
  open: boolean
  details: { recipient: string; amount: number; note?: string }
  // Fixed UUID v4 generated by the parent once per transfer attempt.
  idempotencyKey: string
  onSuccess: (transactionId?: string) => void
  onClose: () => void
}

export function TransferOtpModal({
  open,
  details,
  idempotencyKey,
  onSuccess,
  onClose,
}: TransferOtpModalProps) {
  const [otp, setOtp] = useState("")
  const [submitting, setSubmitting] = useState(false)
  const [sending, setSending] = useState(false)
  const [cooldown, setCooldown] = useState(RESEND_SECONDS)
  const requestedKey = useRef<string | null>(null)

  const sendOtp = useCallback(
    async (silent = false) => {
      setSending(true)
      try {
        // action=TRANSFER: backend dispatches the transfer OTP.
        await requestOtp({ action: "TRANSFER" })
        setCooldown(RESEND_SECONDS)
        if (!silent) toast.success("Đã gửi lại mã OTP.")
      } catch (error) {
        toast.error(getErrorMessage(error))
      } finally {
        setSending(false)
      }
    },
    [],
  )

  // Request the OTP once each time the modal opens for a new idempotency key.
  useEffect(() => {
    if (!open) return
    if (requestedKey.current === idempotencyKey) return
    requestedKey.current = idempotencyKey
    setOtp("")
    void sendOtp(true)
  }, [open, idempotencyKey, sendOtp])

  useEffect(() => {
    if (!open || cooldown <= 0) return
    const id = setInterval(() => setCooldown((c) => Math.max(0, c - 1)), 1000)
    return () => clearInterval(id)
  }, [open, cooldown])

  async function handleConfirm() {
    if (submitting) return
    if (otp.length !== 6) {
      toast.error("Vui lòng nhập đủ 6 số.")
      return
    }
    setSubmitting(true)
    try {
      const payload: TransferInput = { ...details, otp }
      // The SAME idempotencyKey is reused across automatic retries inside transfer().
      const res = await transfer(payload, idempotencyKey)
      toast.success("Chuyển tiền thành công!")
      onSuccess(res.transactionId)
    } catch (error) {
      toast.error(getErrorMessage(error))
      setOtp("")
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        if (!next && !submitting) onClose()
      }}
    >
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-xl bg-accent text-accent-foreground">
            <ShieldCheck className="h-6 w-6" aria-hidden="true" />
          </div>
          <DialogTitle className="text-center">Xác thực giao dịch</DialogTitle>
          <DialogDescription className="text-center text-pretty">
            Nhập mã OTP để xác nhận chuyển{" "}
            <span className="font-semibold text-foreground">
              {currency.format(details.amount)}
            </span>{" "}
            đến <span className="font-semibold text-foreground">{details.recipient}</span>.
          </DialogDescription>
        </DialogHeader>

        <div className="py-2">
          <OtpInput value={otp} onChange={setOtp} disabled={submitting} />
        </div>

        <p className="text-center text-xs text-muted-foreground">
          {cooldown > 0 ? (
            <span className="tabular-nums">Gửi lại mã sau {cooldown}s</span>
          ) : (
            <button
              type="button"
              onClick={() => sendOtp(false)}
              disabled={sending}
              className="font-semibold text-primary hover:underline disabled:opacity-50"
            >
              {sending ? "Đang gửi..." : "Gửi lại mã OTP"}
            </button>
          )}
        </p>

        <DialogFooter className="sm:flex-col sm:gap-2">
          <Button
            onClick={handleConfirm}
            disabled={submitting || otp.length !== 6}
            className="h-11 w-full text-base"
          >
            {submitting ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Đang xử lý giao dịch...
              </>
            ) : (
              "Xác nhận chuyển tiền"
            )}
          </Button>
          <Button
            variant="ghost"
            onClick={onClose}
            disabled={submitting}
            className="w-full"
          >
            Hủy
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
