package com.QuoocCuongwf.EFEWallet.AuthService.enums;

public enum Permission {
    VIEW_WALLET,
    CREATE_WALLET,
    UPDATE_WALLET,
    DELETE_WALLET,

    TRANSFER,
    DEPOSIT,
    WITHDRAW,
    VIEW_TRANSACTION,

    VIEW_PROFILE,
    UPDATE_PROFILE,
    DELETE_ACCOUNT,

    CHANGE_PASSWORD,
    LOGOUT,
    REFRESH_TOKEN,

    ADMIN_VIEW_ALL_WALLETS,
    ADMIN_VIEW_ALL_TRANSACTIONS,
    ADMIN_MANAGE_USERS,
    ADMIN_MANAGE_ROLES,
    ADMIN_MANAGE_PERMISSIONS
}
